{% set version = '1.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-htmlwidgets
  version: {{ version|replace("-", "_") }}

source:
  fn: htmlwidgets_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/htmlwidgets_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/htmlwidgets/htmlwidgets_{{ version }}.tar.gz
  sha256: 1a7d21c1f3306d53a36c05d6ea7873ddeffeda654cd9be689b6d78e62a688411

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-htmltools >=0.3
    - r-jsonlite >=0.9.16
    - r-yaml
  run:
    - r-base
    - r-htmltools >=0.3
    - r-jsonlite >=0.9.16
    - r-yaml

test:
  commands:
    - $R -e "library('htmlwidgets')"           # [not win]
    - "\"%R%\" -e \"library('htmlwidgets')\""  # [win]

about:
  home: https://github.com/ramnathv/htmlwidgets
  license: MIT
  summary: A framework for creating HTML widgets that render in various contexts including the
    R console, 'R Markdown' documents, and 'Shiny' web applications.
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - halldc
