{% set version = "1.5.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-htmlwidgets
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/htmlwidgets_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/htmlwidgets/htmlwidgets_{{ version }}.tar.gz
  sha256: 1a3fc60f40717de7f1716b754fd1c31a132e489a2560a278636ee78eba46ffc1

build:
  merge_build_host: true  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-htmltools >=0.3.0
    - r-jsonlite >=0.9.16
    - r-yaml
  run:
    - r-base
    - r-htmltools >=0.5.4
    - r-jsonlite >=0.9.16
    - r-yaml

test:
  commands:
    - $R -e "library('htmlwidgets')"           # [not win]
    - "\"%R%\" -e \"library('htmlwidgets')\""  # [win]

about:
  home: http://htmlwidgets.org
  dev_url: https://github.com/ramnathv/htmlwidgets
  license: MIT
  summary: A framework for creating HTML widgets that render in various contexts including the R console, 'R Markdown' documents, and 'Shiny' web applications.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - halldc
