bot:
  abi_migration_branches:
  - v1.5
  automerge: true
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  win: azure
